### ISSUE TITLE
Thousands of requests per second to Docker Cloud

### ISSUE THREAD

**Issue by fermayo** [willrstern/docker-cloud-nginx-load-balancing#22]
It's Fernando from Docker Cloud. We are seeing thousands of requests per second from containers that run this code. Could anyone please have a look to improve caching and reducing the number of API requests done to Docker Cloud? We'll be adding more restrictive API throttling on our side that will brake it.

Thanks!

**Comment by willrstern** [comment]
Sure thing!  I think that would help it's efficiency anyway.

**Comment by willrstern** [comment]
Why this is happening:
- a service reloads
- each container event triggers a nginx re-inspect
- inspect means getting all containers to see which to balance (say 25)
- if you have 2LB's for failover and a 3-container service, that's 25*2*3 (150) API calls per reload

The real issue is that we're using an API like a registry.  The correct solution is probably to use etcd/consul and something like registrator.

I loved the idea of a plug-and-play container just "working" with Docker Cloud, but I think it's probably the wrong approach.

**Comment by fermayo** [comment]
So do you need to fetch each container details, or would the container list be sufficient? The container list can return up to 100 records on one call, but not all attributes are available.

**Comment by fermayo** [comment]
Actually the calls that I see being called more often are for the `/api/infra/v1/node/` endpoint. Do you use it?

**Comment by willrstern** [comment]
@fermayo The 2 things this needs to run are:
* env vars for each `service`
* internal ips for each `container`

**So if the `service inspect` returned ip's for each container, then service discovery with the Docker Cloud API would work with much fewer requests**

If service registration were with Etcd or Consul, it'd just make one request to `/services/?recurse=true` or at most 2 `/services/web` & `/services/otherservice`

**Comment by willrstern** [comment]
@fermayo no, this container doesn't use that endpoint.
